name: "Digital Ocean Actions - Spaces Download"

description: "Download objects stored inside Digital Ocean Spaces"

branding:
  icon: "arrow-down"
  color: "blue"

inputs:
  access_key:
    description: "Digital Ocean Spaces access key"
    required: true
  secret_key:
    description: "Digital Ocean Spaces secret key"
    required: true
  space_name:
    description: "Digital Ocean Spaces space name"
    required: true
  space_region:
    description: "Digital Ocean Spaces space region"
    required: true
  source:
    description: "Path to the remote source file"
    required: true
  out_dir:
    description: "Path to local output directory"
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.access_key }}
        aws-secret-access-key: ${{ inputs.secret_key }}
        aws-region: ${{ inputs.space_region }}

    - name: Download file from Digital Ocean Spaces via AWS CLI
      run: |
        aws s3 cp --endpoint=https://${{ inputs.space_region }}.digitaloceanspaces.com s3://${{ inputs.space_name }}/${{ inputs.source }} ${{ inputs.out_dir }}
        
      shell: bash
